name: fetosense_remote_flutter
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_launcher_icons: ^0.14.2
  flutter_local_notifications: ^19.1.0
  flutter_plugin_android_lifecycle: ^2.0.26
  bloc: ^9.0.0
  equatable: ^2.0.5

  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0

  flutter_native_splash: ^2.4.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  get_it: ^8.0.3
  fluttertoast: ^8.2.2
  pdf: ^3.10.1
  permission_handler: ^12.0.0+1
  printing: ^5.10.4
  intl: ^0.20.2
  url_launcher: ^6.1.11
  quiver: ^3.2.2
  connectivity_plus:
  curved_navigation_bar: ^1.0.3
  preferences:
    path: ./preferences-5.2.1
  font_awesome_flutter: ^10.4.0
  flutter_barcode_scanner: ^2.0.0
  device_info: ^2.0.3
  flutter_svg: ^2.0.5
  youtube_player_flutter: ^9.1.1
  scan: 1.6.0
  upgrader:
  image_picker: ^1.0.4
  webview_flutter: ^4.10.0
  appwrite: ^15.0.0
  flutter_lints: ^5.0.0
  go_router: ^15.0.0
  http:
  onnxruntime: ^1.4.0
  tflite_flutter: ^0.11.0
#  tflite_flutter_helper_plus: ^0.0.2

  shared_preferences: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  mocktail:
  url_launcher_platform_interface:
  flutter_inappwebview_platform_interface:
  patrol:
  patrol_finders:

flutter_icons:
  android: "launcher_icon"
  image_path_android: "images/app_icon.png"
  image_path_ios: "images/app_icon.png"
  ios: true
  image_path: "images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
