name: preferences
description: Create Preference Screens easily with advanced features and subpages
version: 5.2.1
author: redsolver <info@redsolver.net>
homepage: https://gitlab.com/redsolver/preferences

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any

flutter:
