name: Flutter Coverage Report

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify coverage report
        run: |
          if [ ! -f coverage/html/index.html ]; then
            echo "❌ coverage/html/index.html not found. Please generate locally and push it."
            exit 1
          fi
          echo "✅ Coverage report found."

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/html
