name: Flutter CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate mocks (if needed)
        run: flutter pub run build_runner build --delete-conflicting-outputs || true

      - name: Run tests with coverage (ignore failures so report still generates)
        run: |
          mkdir -p coverage
          flutter test --coverage --reporter compact || true

      - name: Generate HTML report
        run: |
          sudo apt-get install -y lcov
          genhtml coverage/lcov.info -o coverage/html

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/html

      - name: Enforce coverage threshold
        run: ./check_coverage.sh
